/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import models.Patient;
import models.Payment;
import models.dao.DAOFactory;

/**
 *
 * @author saadel
 */
public class PaymentPanel extends javax.swing.JPanel  implements ListSelectionListener {

    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel() {
        initComponents();
        creditsTable.setModel(TableModelBuilder.buildPaymentTableModel(DAOFactory.getPatientDAO().all()));
        
        ListSelectionModel selectionModel = creditsTable.getSelectionModel();
        selectionModel.addListSelectionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        creditsTable = new javax.swing.JTable();
        validateButton = new javax.swing.JButton();
        montantTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();

        creditsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Crédit"
            }
        ));
        jScrollPane1.setViewportView(creditsTable);

        validateButton.setText("Valider");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Montant:");

        patientLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        patientLabel.setText("Patient n˚");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validateButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(patientLabel)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientLabel)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(montantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validateButton)
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        String num = null;
        try {
            TableModel model = (TableModel)creditsTable.getModel();
            num = String.valueOf(model.getValueAt(creditsTable.getSelectedRow(), 0));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner un patient", "Erreur", JOptionPane.ERROR_MESSAGE);        
        }
        
        if(num != null) {
            try {
                Patient currentPatient = DAOFactory.getPatientDAO().find(num);
                double dhs = Double.parseDouble(montantTextField.getText());
                double credit = currentPatient.getCredit();
                if( credit - dhs >= 0) {
                    currentPatient.setCredit(credit - dhs);
                    DAOFactory.getPatientDAO().update(currentPatient);
                    Payment pay = new Payment();
                    pay.setAmount(dhs);
                    pay.setPatient(currentPatient);
                    DAOFactory.getPaymentDAO().create(pay);
//                    JOptionPane.showMessageDialog(this, "Paiement effectué", "OK", JOptionPane.INFORMATION_MESSAGE);
                    try {
                        creditsTable.setModel(TableModelBuilder.buildPaymentTableModel(DAOFactory.getPatientDAO().all()));
                    } catch (Exception e) {
                        creditsTable.repaint();
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Montant entré invalide !", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            
            } catch (Exception e) {
                System.out.println("Erreur lors de la validation" + e);
            }
        }
    }//GEN-LAST:event_validateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable creditsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField montantTextField;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() == creditsTable.getSelectionModel() && e.getValueIsAdjusting()) {
            
            TableModel model = (TableModel)creditsTable.getModel();
            String num = String.valueOf(model.getValueAt(creditsTable.getSelectedRow(), 0));
           
            Patient patientSelected = DAOFactory.getPatientDAO().find(num);
            
            patientLabel.setText("Patient N˚ " + num);
        }
    }
}
