/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import models.Allergy;
import models.Consultation;
import models.Drug;
import models.PatientInfo;
import models.dao.DAOFactory;

/**
 *
 * @author otm
 */
public class prescriptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form prescriptionFrame
     */
    Consultation consultation;
    Vector<PatientInfo> allInfos ;
    Vector<Drug> allDrugs ;
    Vector<Allergy> allAllergies;
    Vector<PatientInfo> selectedInfos ;
    Vector<Drug> selectedDrugs ;
    Vector<Allergy> selectedAllergies;
    public prescriptionFrame(Consultation Consultation) {
        initComponents();
        this.consultation = Consultation;
        selectedInfos = new Vector<PatientInfo>();
        selectedDrugs = new Vector<Drug>();
        selectedAllergies= new Vector<Allergy>();
        allInfos = DAOFactory.getPatientInfoDAO().all();
       
        for (PatientInfo Info : allInfos) {
            infoChoice.addItem(Info.getProperty());
        }
        
        allDrugs = DAOFactory.getDrugDAO().all();
        for (Drug Drug : allDrugs) {
            drugChoice.addItem(Drug.getDrugName());
        }
        
        allAllergies = DAOFactory.getAllergyDAO().all();
        for (Allergy Allergy : allAllergies) {
            allergyChoice.addItem(Allergy.getAllergyName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagnostiqueText = new javax.swing.JTextArea();
        allergyChoice = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        drugChoice = new javax.swing.JComboBox();
        addDrug = new javax.swing.JButton();
        undoDrug = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        drugDesc = new javax.swing.JTextArea();
        valueText = new javax.swing.JTextField();
        dateInfo = new org.jdesktop.swingx.JXDatePicker();
        infoChoice = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addAllergy = new javax.swing.JButton();
        undoAllergy = new javax.swing.JLabel();
        undoinfo = new javax.swing.JLabel();
        allergies = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        drugList = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        infos = new javax.swing.JTextArea();
        addInfoButton = new javax.swing.JButton();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("medcinium");

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        jLabel1.setText("Diagnostique");

        jLabel2.setText("Description");

        jLabel3.setText("Alllergie");

        diagnostiqueText.setColumns(20);
        diagnostiqueText.setRows(5);
        jScrollPane2.setViewportView(diagnostiqueText);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addDrug.setText("+");
        addDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugActionPerformed(evt);
            }
        });

        undoDrug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Undo.png"))); // NOI18N
        undoDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoDrugMouseClicked(evt);
            }
        });

        drugDesc.setColumns(20);
        drugDesc.setRows(5);
        jScrollPane3.setViewportView(drugDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(drugChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addDrug))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(undoDrug)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(undoDrug)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drugChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addDrug)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoChoiceActionPerformed(evt);
            }
        });

        jLabel5.setText("Infos");

        jLabel6.setText("médicament");

        addAllergy.setText("+");
        addAllergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllergyActionPerformed(evt);
            }
        });

        undoAllergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Undo.png"))); // NOI18N
        undoAllergy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoAllergyMouseClicked(evt);
            }
        });

        undoinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Undo.png"))); // NOI18N
        undoinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoinfoMouseClicked(evt);
            }
        });

        drugList.setEditable(false);
        drugList.setColumns(20);
        drugList.setRows(5);
        jScrollPane4.setViewportView(drugList);

        infos.setColumns(20);
        infos.setRows(5);
        jScrollPane5.setViewportView(infos);

        addInfoButton.setText("+");
        addInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInfoButtonActionPerformed(evt);
            }
        });

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allergyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addAllergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undoAllergy))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(allergies, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(valueText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addInfoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undoinfo))
                            .addComponent(jScrollPane4)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undoinfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(infoChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addInfoButton))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undoAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(allergyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addAllergy)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allergies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valider)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private int i=0;
    private void addDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugActionPerformed
        String chaine="";
        selectedDrugs.add(allDrugs.get(drugChoice.getSelectedIndex()));
        selectedDrugs.get(selectedDrugs.size()-1).setDrugDescription(drugDesc.getText());
        for (Drug d : selectedDrugs) {
            chaine += d.getDrugName()+" : "+d.getDrugDescription()+"\n";
        }
        drugList.setText(chaine);
        drugDesc.setText("");
    }//GEN-LAST:event_addDrugActionPerformed

    private void infoChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoChoiceActionPerformed

    private void addAllergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllergyActionPerformed
        String chaine="";
        selectedAllergies.add(allAllergies.get(allergyChoice.getSelectedIndex()));
        for (Allergy S : selectedAllergies) {
            chaine += S.getAllergyName()+"; ";
        }
        allergies.setText(chaine);
    }//GEN-LAST:event_addAllergyActionPerformed

    private void undoAllergyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoAllergyMouseClicked
        try {
             selectedAllergies.remove(selectedAllergies.size()-1);
        System.out.println(selectedAllergies);
        String chaine="";
        for (Allergy S : selectedAllergies) {
            chaine += S.getAllergyName()+"; ";
        }
        allergies.setText(chaine);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }
       
    }//GEN-LAST:event_undoAllergyMouseClicked

    private void undoDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoDrugMouseClicked
      try {
        selectedDrugs.remove(selectedDrugs.size()-1);
        String chaine="";
        for (Drug d : selectedDrugs) {
            chaine += d.getDrugName()+" : "+d.getDrugDescription()+"\n";
        }
        drugList.setText(chaine);
        drugDesc.setText("");
         }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_undoDrugMouseClicked

    private void undoinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoinfoMouseClicked
     
         try {
        selectedInfos.remove(selectedInfos.size()-1);
        String chaine="";
        for (PatientInfo info : selectedInfos) {
           chaine += info.getProperty()+"   "+info.getValue()+"   "+info.getDateAdded()+"\n";
        }
        infos.setText(chaine);
        valueText.setText("");
         }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_undoinfoMouseClicked

    private void addInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInfoButtonActionPerformed
       
        String chaine="";
        selectedInfos.add(allInfos.get(infoChoice.getSelectedIndex()));
        selectedInfos.get(selectedInfos.size()-1).setValue(valueText.getText());
        selectedInfos.get(selectedInfos.size()-1).setDateAdded(new Date(dateInfo.getDate().getTime()));
        for (PatientInfo info : selectedInfos) {
            chaine += info.getProperty()+"   "+info.getValue()+"   "+info.getDateAdded()+"\n";
        }
        infos.setText(chaine);
        valueText.setText("");
    }//GEN-LAST:event_addInfoButtonActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        consultation.setDescription(descriptionText.getText());
        consultation.setDiagnostics(diagnostiqueText.getText());
        consultation.setStatus("finished");
        
        if(DAOFactory.getConsultationDAO().update(consultation))
        {
        for (PatientInfo selAllInfo : selectedInfos) {
            
            DAOFactory.getConsultationDAO().contient(consultation, selAllInfo);
        }
        
        for (Drug drug : selectedDrugs) {
            
            DAOFactory.getConsultationDAO().introduit(consultation, drug);
        }
        for (Allergy allergy : selectedAllergies) {
            
            DAOFactory.getConsultationDAO().renseigne(consultation, allergy);
        }
        dispose();
        }else
        {
           JOptionPane.showMessageDialog(this, "Erreur de création", "Erreur", JOptionPane.ERROR_MESSAGE);        
  
        }
        
    }//GEN-LAST:event_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prescriptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prescriptionFrame(DAOFactory.getConsultationDAO().find(new Integer(1).toString())).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAllergy;
    private javax.swing.JButton addDrug;
    private javax.swing.JButton addInfoButton;
    private javax.swing.JLabel allergies;
    private javax.swing.JComboBox allergyChoice;
    private org.jdesktop.swingx.JXDatePicker dateInfo;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JTextArea diagnostiqueText;
    private javax.swing.JComboBox drugChoice;
    private javax.swing.JTextArea drugDesc;
    private javax.swing.JTextArea drugList;
    private javax.swing.JComboBox infoChoice;
    private javax.swing.JTextArea infos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel undoAllergy;
    private javax.swing.JLabel undoDrug;
    private javax.swing.JLabel undoinfo;
    private javax.swing.JButton valider;
    private javax.swing.JTextField valueText;
    // End of variables declaration//GEN-END:variables
}
